"""
Communication and Message Models

Tracks all communication related to cases.
"""

from sqlalchemy import Column, String, Text, Boolean, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from sqlalchemy import DateTime

from src.models.base import Base
import enum


class CommunicationChannel(str, enum.Enum):
    """Communication channel."""
    EMAIL = "email"
    LETTER = "letter"
    FAX = "fax"
    PHONE = "phone"
    PORTAL = "portal"
    BEEA = "beea"  # Elektronischer Rechtsverkehr


class MessageDirection(str, enum.Enum):
    """Direction of a message."""
    INBOUND = "in"
    OUTBOUND = "out"


class MessageStatus(str, enum.Enum):
    """Status of a message."""
    DRAFT = "draft"
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    SENT = "sent"
    DELIVERED = "delivered"
    READ = "read"
    FAILED = "failed"
    CANCELLED = "cancelled"


class Communication(Base):
    """
    Communication thread.

    Groups related messages together.
    """

    __tablename__ = "communications"

    # Case Reference
    case_id = Column(
        UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Thread Info
    channel = Column(String(50), nullable=False)  # email, letter, etc.
    subject = Column(String(500))
    status = Column(String(50), default="active")  # active, closed, archived

    # Participants
    participants = Column(JSONB, default=[])  # List of party IDs or emails

    # Metadata
    metadata = Column(JSONB, default={})

    # Relationships
    case = relationship("Case", back_populates="communications")
    messages = relationship("Message", back_populates="thread", lazy="dynamic",
                          order_by="Message.sent_at")

    def __repr__(self) -> str:
        return f"<Communication(id={self.id}, subject='{self.subject}')>"


class Message(Base):
    """
    Individual message within a communication thread.
    """

    __tablename__ = "messages"

    # Thread Reference
    thread_id = Column(
        UUID(as_uuid=True),
        ForeignKey("communications.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Direction
    direction = Column(String(10), nullable=False)  # 'in' or 'out'

    # Sender/Recipient
    from_party_id = Column(UUID(as_uuid=True), ForeignKey("parties.id"), nullable=True)
    from_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    from_email = Column(String(255))
    from_name = Column(String(255))

    to_party_id = Column(UUID(as_uuid=True), ForeignKey("parties.id"), nullable=True)
    to_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    to_email = Column(String(255))
    to_name = Column(String(255))

    # Content
    subject = Column(String(500))
    body_text = Column(Text)
    body_html = Column(Text)

    # Timestamps
    sent_at = Column(DateTime(timezone=True))
    delivered_at = Column(DateTime(timezone=True))
    read_at = Column(DateTime(timezone=True))

    # Status
    status = Column(String(50), default=MessageStatus.DRAFT.value)

    # AI Draft (if generated by AI)
    is_ai_generated = Column(Boolean, default=False)
    ai_draft_id = Column(UUID(as_uuid=True), nullable=True)  # Reference to ai_drafts table

    # Attachments (stored separately in documents)
    attachments = Column(JSONB, default=[])  # List of document IDs

    # Metadata
    metadata = Column(JSONB, default={})

    # Relationships
    thread = relationship("Communication", back_populates="messages")

    # Indexes
    __table_args__ = (
        Index("ix_messages_thread_sent", "thread_id", "sent_at"),
        Index("ix_messages_status", "status"),
    )

    def __repr__(self) -> str:
        return f"<Message(id={self.id}, direction={self.direction})>"
